### ISSUE TITLE
Add eth1 load balancer option

### ISSUE THREAD

**Issue by yorickdowne** [eth2-educators/eth2-docker#40]
Give users the option to use https://github.com/emeraldpay/dshackle as a load balancer for eth1 source, e.g. infura and geth

**Comment by yorickdowne** [comment]
From discord: "You can point it at your local node, and Infura as a fallback node. Point your beacon node at it, profit."

**Comment by MysticRyuujin** [comment]
The way that I do it is I configured a `dshackle.yaml` file in the build folder and just build it with:
```
FROM emeraldpay/dshackle:0.8.3
COPY dshackle.yaml /etc/dshackle/dshackle.yaml
```

But I'm not sure if that aligns with your workflows.

Config reference is here:
https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc

My config looks like this:

```
Host: 0.0.0.0
port: 2449
tls:
  enabled: false

proxy:
  host: 0.0.0.0
  port: 8545
  tls:
    enabled: false
  routes:
    - id: goerli
      blockchain: goerli

cluster:
  defaults:
    - chains:
        - goerli
      options:
        min-peers: 10
  upstreams:
    - id: geth
      chain: goerli
      labels:
        provider: geth
        nodetype: full
      methods:
        enabled:
          - name: eth_chainId
          - name: eth_getLogs
      connection:
        ethereum:
          rpc:
            url: "http://geth:8545"
          ws:
            url: "ws://geth:8545"
    - id: infura
      chain: goerli
      role: fallback
      labels:
        provider: infura
        nodetype: full
      methods:
        enabled:
          - name: eth_chainId
          - name: eth_getLogs
      connection:
        ethereum:
          rpc:
            url: "https://goerli.infura.io/v3/<my_key>"
          ws:
            url: "wss://goerli.infura.io/ws/v3/<my_key>"

```

and my docker-compse looks like:

```
dshackle:
    container_name: dshackle
    build: ./dshackle
    networks:
      - my-bridge
    ports:
      - '8545:8545'
      - '2449:2449'
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
    depends_on:
      - geth
```

You'll have to change it up to fit into your style/workflow but that should get you started :)
